### PR TITLE
I mode power threshold updates

### PR DESCRIPTION
**Pull request by nelsonand**
This reopens https://github.com/cfs-energy/cfspopcon/pull/46#event-12848216546 and closes https://github.com/cfs-energy/cfspopcon/pull/56, now merging just the new threshold formulas into main.

The PR contains simple updates to the I-mode LI power threshold and taue scalings from Amanda Hubbard. Addresses standing issue https://github.com/cfs-energy-internal/internal-cfspopcon/issues/149.

### CODE REVIEW

**Comment by nelsonand** [comment]
@tbody-cfs I think this is all that is needed for the `P_LI` threshold additions

**Comment by tbody-cfs** [comment]
Hi @nelsonand and @aarooshgr,

Thanks for the work!! I've made a small edit which lets us switch the confinement scaling using the `input.yaml` file. 

plot_popcon
plot_popcon
plot_popcon

**Review by tbody-cfs — CHANGES_REQUESTED** [review]
Could you pull in 0b80d7d4dc96c42248bf27bf6185103ca1473bb9 from the I_mode_updates branch?

**Comment by aarooshgr** [comment]
Hi Tom,

Sure, I could do that. I’m away from my computer at the moment so I can get
to it this evening

**Comment by aarooshgr** [comment]
So, I just remembered that I don't have the access to push a commit to main... @nelsonand would you be able to do this?

**Comment by tbody-cfs** [comment]
@nelsonand @aarooshgr could you add the following to `docs/doc_sources/physics_glossary.rst`

At the end is fine. Make sure to match the indentation of the existing file
```
  confinement_power_scaling
    A :class:`~cfspopcon.named_options.ConfinementPowerScaling` indicating which confinement mode power-threshold scaling to use.

```

**Comment by aarooshgr** [comment]
> @nelsonand @aarooshgr could you add the following to `docs/doc_sources/physics_glossary.rst`
> 
> At the end is fine. Make sure to match the indentation of the existing file
> 
> ```
>   confinement_power_scaling
>     A :class:`~cfspopcon.named_options.ConfinementPowerScaling` indicating which confinement mode power-threshold scaling to use.
> ```

Hi Tom, just pushed this change to the I_mode_updates branch of my fork. Please let me know if you need anything else

**Review by tbody-cfs — APPROVED** [review]

**Comment by nelsonand** [comment]
Thanks @tbody-cfs !

**Pull request merged**
